  
ARG GO_VERSION=1.13

FROM golang:${GO_VERSION}-alpine AS builder

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*

RUN mkdir -p /app
WORKDIR /app

COPY . .
RUN go mod download
RUN go build -o ./cmd/redirect/bin ./cmd/redirect

FROM alpine:latest

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*


COPY --from=builder /app/cmd/redirect/bin ./app/cmd/redirect/
COPY --from=builder /app/web/ ./web/
COPY --from=builder /app/.env .


EXPOSE 8080 

ENTRYPOINT ./app/cmd/redirect/bin 